### ISSUE TITLE
Launch specific HBRelog profiles from command-line

### ISSUE THREAD

**Issue by Enf0** [aash/HBRelog#14]
It would be great if there was a command-line parameter to auto-start one or more specific HBRelog profiles from the command-line.
This way, it would make it easier to schedule specific tasks or series of tasks through e.g. Windows Task Scheduler.

_Copy-pase from #15._
I think it would be nice with a task that will (gracefully) log out of WoW, exit the client and then shut down Honorbuddy/HBRelog.

**Comment by aash** [comment]
Looks good.

**Comment by aash** [comment]
@Enf0 If I understand correctly, you want a command line interface for HBRelog, in order to have automation capability. So, for example you would pass some commands from the command line:

```
$ hbrelog-cli.exe start-profile <profile-name>
<profile-name> has been started.

$ hbrelog-cli.exe stop-profile <profile-name>
<profile-name> has been stopped.

$ hbrelog-cli.exe close
<xxx-profile-name> has been stopped.
<yyy-profile-name> has been stopped.
<zzz-profile-name> has been stopped.
HBRelog closed.
```

Did I understand correctly?

P.S. I've merged the two issues because they are related. Feel free to edit your initial post.

**Comment by Enf0** [comment]
Not necessarily a separate CLI. HBRelog already has a few command-line arguments such as:

```
Command-line Arguments

/autostart - starts all enabled profiles on start-up
/WowDelay=DELAY_IN_SECONDS - the delay in-between starting multiple WoW processes
/HBDelay=DELAY_IN_SECONDS - the delay in-between starting multiple HB processes from same path
```

Extending this with my suggestions would make it possible to control HBRelog from the command-line (for use in scripts/scheduled tasks) while still keeping the GUI open.

`pause-profile <profile-name>` might also be a useful command.

**Comment by aash** [comment]
@Enf0 HBRelog command line arguments modify behavior of the program instance. But you are asking of new interface to the core functions of HBRelog. New interface and behavior modification is different things by nature.

**Comment by Enf0** [comment]
I understand. I just started using Honorbuddy and I feel like what is really lacking is a proper out-of-game manager. HBRelog/aRelog serve some basic purposes, but still leave a lot to be desired.

I used to bot in Diablo II and many of the OOG managers there were really great.

Anyway, I've partially solved my issues by making a batch script that swaps between different Setting.xmlfiles into AppData depending on which task(s) I want to run. This seems to work, but is far from a perfect solution.

**Comment by aash** [comment]
@Enf0 Why you have closed this issue?
I'm reopening it because I like the idea and actually I've thought of it before.

**Comment by Enf0** [comment]
Oh, sorry. I thought you declined my suggestion. Nevermind then, carry on :)

If you need any more suggestions, I have a few ideas on how to improve HBRelog as an out-of-game manager!

**Comment by aash** [comment]
Feel free to add new issues with `enhacement` tag. Also you can describe usage model, scenarios.

**Comment by Enf0** [comment]
Will do! I've taken a log at ReBot's Relogger and it has some functionality which I think would be great in HBRelog, so I'll admit to stealing some ideas from there.

By the way, it seems like only the project owner can assign labels to new issues.
